[package]
name = "binary-logistic-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15.6", features = ["approx", "std"] }
polars = { version = "0.40.0", features = ["ndarray"] }
